### ISSUE TITLE
Change blur opacity

### ISSUE THREAD

**Issue by rnayabed** [kieferlam/JavaFX-Blur#1]
I'm thinking of shifting my [app's](https://github.com/dubbadhar/gramophy) design language from Material Design to Fluent Design. 

Your library currently doesn't support changing the blur opacity.
Also, is it possible to change the acrylic background color/hue?

Here's a look (Still updating components from Material to Fluent Design) :

![image](https://user-images.githubusercontent.com/25760501/73123702-b1ef3e00-3fb8-11ea-8f56-ec94d8ad3f2a.png)

Overall, a super awesome project!

**Comment by kieferlam** [comment]
Unfortunately (as far as I'm aware), the native Windows call to set the acrylic blur effect doesn't allow changing the opacity or strength of the blur. You should be able to use a translucent fill with a colour on the scene fill/background although I haven't tested this.

**Comment by rnayabed** [comment]
Can you send me an article/guide me on how to do this? Thanks!

**Comment by kieferlam** [comment]
https://stackoverflow.com/questions/12717487/how-to-implement-a-transparent-pane-with-non-transparent-children

This might help. Just set the fill's opacity to 0.5 or something. E.g. rgba(200, 80, 80, 0.5) for a redish hue.

**Comment by rnayabed** [comment]
Thanks! Will Check it later :)
