### ISSUE TITLE
i can't get the .jar file?? where it is??

### ISSUE THREAD

**Issue by ahmeedev** [kieferlam/JavaFX-Blur#3]
I want to add this library to my JavaFX project, but I don't find anyway? plz, guide me.

**Comment by mzaryabrafique** [comment]
Here is Jar and DLL file. You can download the JavaFXBlur_0.0.2.zip and inside you find the file.
Visit this link to get the zip file: [JavaFX-Blur](https://github.com/kieferlam/JavaFX-Blur/releases/tag/0.0.2)

**Comment by ahmeedev** [comment]
Thanks, Zaryab-Programmer.
